Feature/notebooks
pmgbergen/DarIA pull request #42
Opened 2022-09-19 14:16 UTC by EStorvik

Created both a notebook for showing some of the basic image manipulation tools in DarIA, and the curvature correction procedure. I am not too happy with the curvature correction part and will create a class and remake the notebook soon. Additionally, some files related to the notebooks were improved upon.

2022-09-19 18:08 UTC, jwboth commented
@EStorvik , what is your sense? Shall we make this PR a draft and you plan to work on this, or is this meant to be reviewed and merged before further updates will be made?

2022-09-21 11:14 UTC, jwboth requested changes
Nice! See minor comments below.

2022-09-21 11:17 UTC, EStorvik commented on src/daria/utils/conversions.py
> +def BGR2RED(img: da.Image) -> da.Image:
Yes, this was my plan!

2022-09-21 11:17 UTC, EStorvik commented on src/daria/utils/conversions.py
>      return img[:, :, ::-1]
Agreed

2022-09-21 11:18 UTC, EStorvik commented on src/daria/image/image.py
> +        if len(self.img.shape) == 3:
I think that this actually worked, but I will anyways remove it with the inclusions of the colorspace tag

2022-09-21 11:19 UTC, jwboth commented
And remove the empty notebook.

2022-09-21 15:53 UTC, jwboth approved these changes
Whenever you think this is finished, feel free to merge!

2022-09-21 15:58 UTC, merged